# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjectDetection
                                 A QGIS plugin
 This plugin can be used to train and test object detection models on satellite imagery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-26
        copyright            : (C) 2021 by Centre for Development of Advanced Computing, Pune
        email                : rshindihatti@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ObjectDetection class from file ObjectDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .object_detection import ObjectDetection
    return ObjectDetection(iface)
